# Generated by Django 5.2.1 on 2025-05-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayvan İlanı', 'verbose_name_plural': 'Hayvan İlanları'},
        ),
    ]
