# Generated by Django 5.2.1 on 2025-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_application_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('ankara', 'Ankara'), ('izmir', 'İzmir')], max_length=50),
        ),
    ]
